### ISSUE TITLE
Phase 1 - Initial Implementation

### ISSUE THREAD

**Issue by nnarain** [nnarain/mapgen2#7]
The scope of this project is to create a tool for generating 2D and 3D terrain maps. It should allow fast iteration of generating terrain maps.

This epic groups issues related to the initial implementation of the map generator. It is the baseline for "getting it to work".

Must:

- [x] Allow for the creation of libnoise modules
- [x] Set the parameters for the libnoise modules, including other noise modules
- [x] Display a 2D terrain map

Should:

- [x] Display output of the individual noise modules (preview)

Following Phase 1 will be a refactoring stage to improve the code without changing functionality.
